language: ruby
cache: bundler # caching bundler gem packages will speed up build
sudo: false
gemfile: docs/Gemfile

# libcurl 
addons:
  apt:
    packages:
    - libcurl4-openssl-dev

# install:
#   - bundle install

script:
  - bundle exec jekyll build -s docs -d _site --config docs/_config_local.yml
  - bundle exec htmlproofer _site --assume-extension --disable-external

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
