language: ruby
cache: bundler # caching bundler gem packages will speed up build

# libcurl 
addons:
  apt:
    packages:
    - libcurl4-openssl-dev

before_install:
  - cd docs

install:
  - bundle install

script:
  - bundle exec jekyll build --config _config_local.yml
  - bundle exec htmlproofer _site --assume-extension --disable-external

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
