nbviewer: "https://nbviewer.jupyter.org/github/hidrokit/notebook/blob/master"
nbviewer_base: "https://nbviewer.jupyter.org"
github: "https://github.com/hidrokit/notebook/blob/master"
rawgithub: "https://raw.githubusercontent.com/hidrokit/notebook/master"
googlecolab: "https://colab.research.google.com/github/hidrokit/notebook/blob/master"
gist_url: "https://gist.github.com"
