name: Jekyll Build
on: 
  push:
    branches:
      - master
  pull_request:
    type: [opened, reopened, synchronize]

jobs:
  jekyll_build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/docs/Gemfile
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    # - run: bundle exec htmlproofer _site --assume-extension --disable-external
    - run: bundle exec jekyll build -s docs -d _site --config docs/_config_local.yml

